<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('sales_returns', function (Blueprint $table) {
            if (!Schema::hasColumn('sales_returns', 'offline_id')) {
                $table->string('offline_id')->nullable()->unique()->after('status')->comment('Unique ID generated by offline POS to prevent duplication');
            }
        });

        Schema::table('quotations', function (Blueprint $table) {
            if (!Schema::hasColumn('quotations', 'offline_id')) {
                $table->string('offline_id')->nullable()->unique()->after('status')->comment('Unique ID generated by offline POS to prevent duplication');
            }
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('sales_returns', function (Blueprint $table) {
            if (Schema::hasColumn('sales_returns', 'offline_id')) {
                $table->dropColumn('offline_id');
            }
        });

        Schema::table('quotations', function (Blueprint $table) {
            if (Schema::hasColumn('quotations', 'offline_id')) {
                $table->dropColumn('offline_id');
            }
        });
    }
};
